"""CMake toolchain wrapper shared by the SDK-based backends.

An OE/Yocto SDK ships a stock CMake toolchain file that is fine for building a
single library against the target sysroot, but not for a colcon workspace of
interdependent ROS packages. Rather than replace it, both the containerised
and the host SDK paths wrap it: include the SDK's own file, then correct the
three things that stop a ROS workspace from configuring.

The wrapper refers to the environment ($ENV{...}) rather than baking in paths
where it can, so the same text works inside a container and on the host, and a
mixin that points at it keeps working for anyone who has sourced the SDK.
"""

WRAPPER_NAME = 'buildx-toolchain.cmake'

# CMake's ${...} syntax collides with str.format, hence %-formatting.
_TEMPLATE = '''\
# Generated by colcon-buildx. Wraps the SDK's own toolchain file.
include("%(toolchain)s")

# 1. The stock OE toolchain builds its sysroot path from
#    ${CMAKE_CURRENT_LIST_DIR}/../../../../.. and never normalizes it. CMake
#    compares prefixes with find roots textually, so a prefix that *is* inside
#    the sysroot but is spelled canonically is not recognised as already rooted:
#    it is re-rooted into a path that does not exist and silently dropped.
set(_buildx_roots "")
foreach(_buildx_root IN LISTS CMAKE_FIND_ROOT_PATH)
  get_filename_component(_buildx_root "${_buildx_root}" REALPATH)
  list(APPEND _buildx_roots "${_buildx_root}")
endforeach()

# 2. CMAKE_FIND_ROOT_PATH_MODE_PACKAGE is ONLY, so find_package() only looks
#    under the find roots. Without the workspace's install prefix among them, a
#    package cannot find the packages built before it in the same workspace.
set(CMAKE_FIND_ROOT_PATH ${_buildx_roots} "%(install_dir)s")

# 3. ros-sdk-env exports AMENT_PREFIX_PATH but not CMAKE_PREFIX_PATH, and sets
#    AMENT_SKIP_SHELL_PATH, which turns off the PATH-based prefix discovery that
#    finds /opt/ros/<distro> on a native install. Without this, the first
#    find_package(ament_cmake) of any ROS package fails.
if(DEFINED ENV{AMENT_PREFIX_PATH})
  string(REPLACE ":" ";" _buildx_ament "$ENV{AMENT_PREFIX_PATH}")
  list(APPEND CMAKE_PREFIX_PATH ${_buildx_ament})
endif()
'''


def wrapper_text(install_dir, toolchain='$ENV{OE_CMAKE_TOOLCHAIN_FILE}'):
    """
    Return the wrapper toolchain file contents.

    Args:
        install_dir: The colcon install prefix, as seen by the build
        toolchain: The SDK toolchain to wrap; by default whatever ros-sdk-env
            exported, resolved when CMake runs

    Returns:
        str: CMake toolchain file contents
    """
    return _TEMPLATE % {'toolchain': toolchain, 'install_dir': install_dir}
