#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 SMAROBIX GmbH
# SPDX-License-Identifier: Apache-2.0

"""Generate the reference pages that are derived from the code.

Writes docs/reference/cli.md from the ``colcon buildx`` argument parser, and
docs/reference/config-keys.md from DEFAULTS and CONFIG_KEYS. With --check it
writes nothing and exits 1 if either page is out of date.

The parser is built the way colcon builds it, so the page describes exactly
the options ``colcon buildx --help`` shows. Everything that varies between
machines or Python versions is kept out of the output: argparse's own usage
and help formatting (its wrapping follows the terminal and its section titles
differ between Python releases) and the expanded home directory in defaults.
"""

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Document the code in this checkout, not whichever copy is installed.
sys.path.insert(0, str(REPO_ROOT))

from colcon_buildx.verb.buildx import (  # noqa: E402
    BuildxVerb, CONFIG_KEYS, DEFAULTS)

CLI_PAGE = REPO_ROOT / 'docs' / 'reference' / 'cli.md'
KEYS_PAGE = REPO_ROOT / 'docs' / 'reference' / 'config-keys.md'

PROG = 'colcon buildx'
USAGE_WIDTH = 79
UNSET = 'unset'
SOURCE_URL = ('https://github.com/smarobix/smarobix-colcon-buildx/blob/main/'
              'colcon_buildx/verb/buildx.py')

GENERATED_NOTE = (
    '<!-- Generated by tools/gen_docs.py; do not edit by hand. '
    'Run `python tools/gen_docs.py` to update it. -->')


def build_verb_parser():
    """Return the argument parser colcon builds for the buildx verb."""
    from colcon_core.command import CustomFormatter, add_subparsers

    parser = argparse.ArgumentParser(
        prog='colcon', formatter_class=CustomFormatter)
    verb = BuildxVerb()
    # colcon sets this when it loads the verb from its entry point.
    verb.VERB_NAME = 'buildx'
    add_subparsers(parser, 'colcon', {'buildx': verb}, attribute='verb_name')
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices['buildx']
    raise RuntimeError('colcon did not create a parser for the buildx verb')


def is_help(action):
    return isinstance(action, argparse._HelpAction)


def metavar(action):
    """The placeholder argparse shows after an option, or None for flags."""
    if action.nargs == 0:
        return None
    if action.metavar is not None:
        return action.metavar
    if action.choices is not None:
        return '{' + ','.join(str(c) for c in action.choices) + '}'
    if action.option_strings:
        return action.dest.upper()
    return action.dest


def usage_part(action):
    """One action as it appears in the usage line."""
    if action.option_strings:
        text = action.option_strings[0]
        mv = metavar(action)
        if mv is not None:
            text += ' ' + mv
        return text if action.required else '[' + text + ']'
    mv = metavar(action)
    if action.nargs == '*':
        return '[' + mv + ' ...]'
    if action.nargs == '+':
        return mv + ' [' + mv + ' ...]'
    if action.nargs == '?':
        return '[' + mv + ']'
    return mv


def usage(parser):
    """The usage line, wrapped the same way whatever the terminal width."""
    optionals = [a for a in parser._actions if a.option_strings]
    positionals = [a for a in parser._actions if not a.option_strings]
    parts = [usage_part(a) for a in optionals + positionals
             if a.help is not argparse.SUPPRESS]
    # Wrapped between parts, never inside one, as argparse does.
    lines = ['usage: ' + PROG]
    indent = ' ' * len(lines[0])
    for part in parts:
        if len(lines[-1]) + 1 + len(part) > USAGE_WIDTH and lines[-1].strip():
            lines.append(indent)
        lines[-1] += ' ' + part
    return '\n'.join(lines)


def expand_help(action, prog):
    """Expand %(default)s and friends the way argparse does."""
    text = action.help or ''
    if '%' not in text:
        return text
    params = dict(vars(action), prog=prog)
    if action.choices is not None:
        params['choices'] = ', '.join(str(c) for c in action.choices)
    try:
        return text % params
    except (KeyError, TypeError, ValueError):
        return text


def format_value(value):
    """A default as it would be written in a config file."""
    if value is None:
        return UNSET
    if isinstance(value, bool):
        return '`true`' if value else '`false`'
    text = str(value)
    home = os.path.expanduser('~')
    if home not in ('', '/', '~') and (
            text == home or text.startswith(home + os.sep)):
        # DEFAULTS expands ~ at import time; keep the page machine-neutral.
        text = '~' + text[len(home):]
    return '`' + text + '`'


def escape_cell(text):
    """Make free text safe inside a GFM table cell.

    Outside code spans, angle brackets would be read as HTML and asterisks as
    emphasis. A pipe ends the cell even inside a code span, so it is escaped
    everywhere, which GFM allows for that reason.
    """
    text = ' '.join(text.split())
    pieces = text.split('`')
    for i, piece in enumerate(pieces):
        if i % 2 == 0:
            piece = (piece.replace('&', '&amp;').replace('<', '&lt;')
                     .replace('>', '&gt;').replace('*', r'\*'))
        pieces[i] = piece.replace('|', r'\|')
    if len(pieces) % 2 == 0:
        # An unmatched backtick: leave the text as it was, escaped.
        return text.replace('|', r'\|')
    return '`'.join(pieces)


def option_label(action):
    mv = metavar(action)
    if action.option_strings:
        names = ', '.join('`' + opt + (' ' + mv if mv else '') + '`'
                          for opt in action.option_strings)
        return escape_cell(names)
    return escape_cell('`' + mv + '`')


def default_for(action):
    if is_help(action):
        return ''
    if action.dest in DEFAULTS:
        return format_value(DEFAULTS[action.dest])
    if action.default is argparse.SUPPRESS:
        return ''
    return format_value(action.default)


def group_title(parser, group):
    """Section title for an argparse group, the same on every Python.

    Python 3.10 renamed argparse's "optional arguments" section to "options",
    so the two built-in groups get fixed titles here.
    """
    if group is parser._positionals:
        return 'Positional arguments'
    if group is parser._optionals:
        return 'General options'
    return group.title


def cli_page(parser):
    lines = [GENERATED_NOTE, '', '# Command-line reference', '']
    if parser.description:
        lines += ['`{}`: {}'.format(PROG, parser.description.strip()), '']
    lines += [
        'Every option of `colcon buildx`, generated from its argument parser: '
        'the same source as `colcon buildx --help`. Any argument not listed '
        'here is passed on to `colcon build`.',
        '',
        'Most options can also be set in a config file; '
        '[config keys](config-keys.md) lists them. The defaults shown apply '
        'when neither the command line nor the config file sets a value.',
        '',
    ]
    lines += ['## Usage', '', '```text', usage(parser), '```', '']

    for group in parser._action_groups:
        actions = [a for a in group._group_actions
                   if a.help is not argparse.SUPPRESS]
        if not actions:
            continue
        lines += ['## ' + group_title(parser, group), '']
        if group.description:
            lines += [group.description.strip(), '']
        if group is parser._positionals:
            lines += ['| Argument | Description |', '|---|---|']
            for action in actions:
                lines.append('| {} | {} |'.format(
                    option_label(action),
                    escape_cell(expand_help(action, PROG))))
        else:
            lines += ['| Option | Default | Description |', '|---|---|---|']
            for action in actions:
                lines.append('| {} | {} | {} |'.format(
                    option_label(action), default_for(action),
                    escape_cell(expand_help(action, PROG))))
        lines.append('')

    if parser.epilog:
        lines += ['## Notes', '', '```text',
                  parser.epilog.strip('\n'), '```', '']
    return '\n'.join(lines)


def keys_page(parser):
    by_dest = {}
    for action in parser._actions:
        if action.option_strings and not is_help(action):
            by_dest.setdefault(action.dest, action)

    lines = [
        GENERATED_NOTE,
        '',
        '# Config file keys',
        '',
        'Every key accepted in `.buildx.conf`, `.buildx.yml` and '
        '`.buildx.yaml`, generated from `DEFAULTS` and `CONFIG_KEYS` in '
        '[`colcon_buildx/verb/buildx.py`]({}). A value on the command line '
        'overrides the config file, which overrides the default. '
        '[Configuration](../config.md) describes the file formats and where '
        'colcon-buildx looks for them.'.format(SOURCE_URL),
        '',
        'Keys may be written with hyphens instead of underscores. Keys whose '
        'flag takes no value are booleans: `true` or `false`.',
        '',
        '| Key | Default | Flag | Description |',
        '|---|---|---|---|',
    ]
    for key in sorted(CONFIG_KEYS):
        action = by_dest.get(key)
        default = format_value(DEFAULTS.get(key))
        flag = option_label(action) if action else ''
        text = escape_cell(expand_help(action, PROG)) if action else ''
        lines.append('| `{}` | {} | {} | {} |'.format(
            key, default, flag, text))
    lines.append('')

    no_key = [a for a in parser._actions
              if not is_help(a) and a.dest not in CONFIG_KEYS
              and a.help is not argparse.SUPPRESS]
    if no_key:
        lines += [
            'These have no config key, and can only be given on the command '
            'line:',
            '',
        ]
        for action in no_key:
            lines.append('- {}: {}'.format(
                option_label(action),
                escape_cell(expand_help(action, PROG))))
        lines.append('')
    return '\n'.join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        '--check', action='store_true',
        help='write nothing; exit 1 if a generated page is out of date')
    args = ap.parse_args(argv)

    parser = build_verb_parser()
    pages = {
        CLI_PAGE: cli_page(parser),
        KEYS_PAGE: keys_page(parser),
    }

    stale = []
    for path, text in pages.items():
        current = path.read_text(encoding='utf-8') if path.exists() else None
        if current == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8')

    for path in stale:
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            print('{} is out of date'.format(rel), file=sys.stderr)
        else:
            print('wrote {}'.format(rel))
    if args.check and stale:
        print('Run `python tools/gen_docs.py` and commit the result.',
              file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
