#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 SMAROBIX GmbH
# SPDX-License-Identifier: Apache-2.0

"""Generate docs/reference.md, the page that is derived from the code.

The page describes every option of ``colcon buildx`` with its config-file
key and default, from the same argument parser that ``colcon buildx --help``
uses, plus the ``--help`` epilog. With --check it writes nothing and exits 1
if the page is out of date.

Everything that varies between machines or Python versions is kept out of
the output: argparse's own usage and help formatting (its wrapping follows
the terminal and its section titles differ between Python releases) and the
expanded home directory in defaults.
"""

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Document the code in this checkout, not whichever copy is installed.
sys.path.insert(0, str(REPO_ROOT))

from colcon_buildx.verb.buildx import (  # noqa: E402
    BuildxVerb, CONFIG_KEYS, DEFAULTS)

PAGE = REPO_ROOT / 'docs' / 'reference.md'

PROG = 'colcon buildx'
USAGE_WIDTH = 79
UNSET = 'unset'
EXAMPLES_URL = ('https://github.com/smarobix/smarobix-colcon-buildx/tree/'
                'main/examples')

GENERATED_NOTE = (
    '<!-- Generated by tools/gen_docs.py; do not edit by hand. '
    'Run `python tools/gen_docs.py` to update it. -->')

# The hand-written part of the page. It lives here so that the page has one
# owner; keep it short and keep the facts in it about the tool, not about
# the boards.
INTRO = '''\
Every option of `colcon buildx`, generated from its argument parser: the same
source as `colcon buildx --help`. Any argument not listed here is passed on to
`colcon build`.

## Methods

`--method`, or `method` in the config file, picks how the build runs.

- **`docker`**, the default. Runs `colcon build --merge-install` inside
  `docker_image`, with `src/` mounted read-only and the container running as
  your user. An image that runs *as* the board is started with `--platform
  docker_platform`, natively or under QEMU; a cross SDK image, recognised by
  its [labels](labels.md), is started without `--platform`, has its SDK
  environment sourced, and builds with the toolchain wrapper and Ninja.
- **`sdk`**. Builds on this Linux host against a Yocto/OE SDK installed here,
  named by `--sdk-env`, with the same toolchain wrapper. `--emit-mixin` also
  writes the settings as a colcon mixin, so a plain `colcon build --mixin
  buildx` can use them after `colcon mixin add buildx
  file://$PWD/.buildx/mixin/index.yaml`.
- **`sysroot`**, experimental. Mounts the board's root filesystem over SSHFS
  and cross-compiles against it on this Linux host, with a CMake toolchain
  file you supply for your aarch64 cross compiler. It needs `--sysroot-host`
  and `--toolchain`, and `user_allow_other` in `/etc/fuse.conf`. aarch64
  boards only, and no Python message bindings.

## Config files

A config file holds the same keys as the options below, one per line as
`key = value` in `.buildx.conf`, or as a YAML mapping in `.buildx.yml` or
`.buildx.yaml`. A key is the option name without the leading `--`, with
underscores or hyphens; on/off options take `true` or `false`; a line that
starts with `#` is a comment. Every run prints the file it read as
`Config file: PATH`. An unknown key is reported and ignored. Commented
examples of every key are in [`examples/`]({examples}).

The search order and the precedence rules, as `--help` prints them:

```text
{epilog}
```
'''

FILES_TABLE = '''\
## Files colcon-buildx writes

All of these are in the workspace root, the first directory at or above
the current one that holds `src/`. Add the ones you use to `.gitignore`.

| Path | Written by |
|---|---|
| `cross_build/` | Every build: colcon's build tree, the toolchain wrapper `buildx-toolchain.cmake`, and with the Docker method colcon's logs. |
| `cross_install/` | Every build. What `--deploy` copies to the board. |
| `log/` | Builds with `--method sdk` or `--method sysroot`, which leave colcon's logs in its usual place. |
| `.buildx-sync-manifest.json` | `--sync-from-device`, and `--install-deps` with the Docker method. |
| `cross_log/sync-packages-*.log` | `--sync-from-device`, when there was something to change. |
| `.buildx/mixin/` | `--emit-mixin` with `--method sdk`. |
'''


def build_verb_parser():
    """Return the argument parser colcon builds for the buildx verb."""
    from colcon_core.command import CustomFormatter, add_subparsers

    parser = argparse.ArgumentParser(
        prog='colcon', formatter_class=CustomFormatter)
    verb = BuildxVerb()
    # colcon sets this when it loads the verb from its entry point.
    verb.VERB_NAME = 'buildx'
    add_subparsers(parser, 'colcon', {'buildx': verb}, attribute='verb_name')
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices['buildx']
    raise RuntimeError('colcon did not create a parser for the buildx verb')


def is_help(action):
    return isinstance(action, argparse._HelpAction)


def metavar(action):
    """The placeholder argparse shows after an option, or None for flags."""
    if action.nargs == 0:
        return None
    if action.metavar is not None:
        return action.metavar
    if action.choices is not None:
        return '{' + ','.join(str(c) for c in action.choices) + '}'
    if action.option_strings:
        return action.dest.upper()
    return action.dest


def usage_part(action):
    """One action as it appears in the usage line."""
    if action.option_strings:
        text = action.option_strings[0]
        mv = metavar(action)
        if mv is not None:
            text += ' ' + mv
        return text if action.required else '[' + text + ']'
    mv = metavar(action)
    if action.nargs == '*':
        return '[' + mv + ' ...]'
    if action.nargs == '+':
        return mv + ' [' + mv + ' ...]'
    if action.nargs == '?':
        return '[' + mv + ']'
    return mv


def usage(parser):
    """The usage line, wrapped the same way whatever the terminal width."""
    optionals = [a for a in parser._actions if a.option_strings]
    positionals = [a for a in parser._actions if not a.option_strings]
    parts = [usage_part(a) for a in optionals + positionals
             if a.help is not argparse.SUPPRESS]
    # Wrapped between parts, never inside one, as argparse does.
    lines = ['usage: ' + PROG]
    indent = ' ' * len(lines[0])
    for part in parts:
        if len(lines[-1]) + 1 + len(part) > USAGE_WIDTH and lines[-1].strip():
            lines.append(indent)
        lines[-1] += ' ' + part
    return '\n'.join(lines)


def expand_help(action, prog):
    """Expand %(default)s and friends the way argparse does."""
    text = action.help or ''
    if '%' not in text:
        return text
    params = dict(vars(action), prog=prog)
    if action.choices is not None:
        params['choices'] = ', '.join(str(c) for c in action.choices)
    try:
        return text % params
    except (KeyError, TypeError, ValueError):
        return text


def format_value(value):
    """A default as it would be written in a config file."""
    if value is None:
        return UNSET
    if isinstance(value, bool):
        return '`true`' if value else '`false`'
    text = str(value)
    home = os.path.expanduser('~')
    if home not in ('', '/', '~') and (
            text == home or text.startswith(home + os.sep)):
        # DEFAULTS expands ~ at import time; keep the page machine-neutral.
        text = '~' + text[len(home):]
    return '`' + text + '`'


def escape_cell(text):
    """Make free text safe inside a GFM table cell.

    Outside code spans, angle brackets would be read as HTML and asterisks as
    emphasis. A pipe ends the cell even inside a code span, so it is escaped
    everywhere, which GFM allows for that reason.
    """
    text = ' '.join(text.split())
    pieces = text.split('`')
    for i, piece in enumerate(pieces):
        if i % 2 == 0:
            piece = (piece.replace('&', '&amp;').replace('<', '&lt;')
                     .replace('>', '&gt;').replace('*', r'\*'))
        pieces[i] = piece.replace('|', r'\|')
    if len(pieces) % 2 == 0:
        # An unmatched backtick: leave the text as it was, escaped.
        return text.replace('|', r'\|')
    return '`'.join(pieces)


def option_label(action):
    mv = metavar(action)
    if action.option_strings:
        names = ', '.join('`' + opt + (' ' + mv if mv else '') + '`'
                          for opt in action.option_strings)
        return escape_cell(names)
    return escape_cell('`' + mv + '`')


def key_label(action):
    """The config-file key of an option, or '' when it has none."""
    if not action.option_strings or action.dest not in CONFIG_KEYS:
        return ''
    return '`' + action.dest + '`'


def default_for(action):
    if is_help(action):
        return ''
    if action.dest in DEFAULTS:
        return format_value(DEFAULTS[action.dest])
    if action.default is argparse.SUPPRESS:
        return ''
    return format_value(action.default)


def group_title(parser, group):
    """Section title for an argparse group, the same on every Python.

    Python 3.10 renamed argparse's "optional arguments" section to "options",
    so the two built-in groups get fixed titles here.
    """
    if group is parser._positionals:
        return 'Positional arguments'
    if group is parser._optionals:
        return 'General options'
    return group.title


def page(parser):
    lines = [GENERATED_NOTE, '', '# colcon buildx reference', '']
    if parser.description:
        lines += ['`{}`: {}'.format(PROG, parser.description.strip()), '']
    lines += [INTRO.format(
        examples=EXAMPLES_URL,
        epilog=(parser.epilog or '').strip('\n'))]
    lines += ['## Options', '',
              'The Key column is the config-file key; an option without one '
              'can only be given on the command line. The default applies '
              'when neither the command line nor the config file sets a '
              'value.',
              '', '```text', usage(parser), '```', '']

    for group in parser._action_groups:
        actions = [a for a in group._group_actions
                   if a.help is not argparse.SUPPRESS and not is_help(a)]
        if not actions:
            continue
        lines += ['### ' + group_title(parser, group), '']
        if group.description:
            lines += [group.description.strip(), '']
        if group is parser._positionals:
            lines += ['| Argument | Description |', '|---|---|']
            for action in actions:
                lines.append('| {} | {} |'.format(
                    option_label(action),
                    escape_cell(expand_help(action, PROG))))
        else:
            lines += ['| Option | Key | Default | Description |',
                      '|---|---|---|---|']
            for action in actions:
                lines.append('| {} | {} | {} | {} |'.format(
                    option_label(action), key_label(action),
                    default_for(action),
                    escape_cell(expand_help(action, PROG))))
        lines.append('')

    lines += [FILES_TABLE]
    return '\n'.join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        '--check', action='store_true',
        help='write nothing; exit 1 if the generated page is out of date')
    args = ap.parse_args(argv)

    text = page(build_verb_parser())
    current = PAGE.read_text(encoding='utf-8') if PAGE.exists() else None
    rel = PAGE.relative_to(REPO_ROOT)
    if current == text:
        return 0
    if args.check:
        print('{} is out of date'.format(rel), file=sys.stderr)
        print('Run `python tools/gen_docs.py` and commit the result.',
              file=sys.stderr)
        return 1
    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text(text, encoding='utf-8')
    print('wrote {}'.format(rel))
    return 0


if __name__ == '__main__':
    sys.exit(main())
